### ISSUE TITLE
can SDWebImage convert image to APNG?

### ISSUE THREAD

**Issue by bizibizi** [SDWebImage/SDWebImageAPNGCoder#3]

**Comment by dreampiggy** [comment]
1. Use the `SDWebImageCoderHelper animatedImageWithFrames:` method, to provide yor frame array to generate a UIAnimatedImage
2. Feed the UIAnimatedImage to `SDWebImageAPNGCoder encodedDataWithImage:image`
3. It's done.

See more in [wiki](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#custom-coder-420) and [documentation](https://sdwebimage.github.io/)

However, this APNG coder repo is already been deprecated, strongly recommended to use SDWebImage 5.0, which is built-in.
